# Generated by Django 3.1 on 2020-08-31 17:07

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(blank=True, max_length=1024, verbose_name='context')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('image', models.ImageField(blank=True, upload_to=posts.models.user_directory_path, verbose_name='image')),
            ],
        ),
    ]
