# Generated by Django 3.1 on 2020-10-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201013_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.BooleanField(default=None, verbose_name='Online'),
            preserve_default=False,
        ),
    ]
