# Generated by Django 3.1 on 2020-10-20 15:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='username'),
            preserve_default=False,
        ),
    ]
