# Generated by Django 3.1 on 2020-10-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
    ]
